env: flex

runtime: nodejs

runtime_config:
  operating_system: "ubuntu22"

manual_scaling:
  instances: 1

entrypoint: npm run start

network:
  # Required for websocket connections
  session_affinity: true
  # Ensure this matches .env
  forwarded_ports:
    - 3001

handlers:
  - url: /.*
    script: auto
    secure: always
