name: CI

on:
  push:
    branches: 
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@2.0.3
        env:
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          BASE_BRANCH: deploy
          BRANCH: master
          FOLDER: dist
          BUILD_SCRIPT: npm install && npm run-script build
          CNAME: elicrow.com
      - name: Add Additional Files
        run: touch "./.nojekyll" && echo "$PWD"

