name: CI

env:
  CNAME: elicrow.com

on:
  push:
    branches: 
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Install Packages
        run: npm install
  
      - name: Build
        run: npm run-script build
      
      - name: Add Required Files
        run: echo "elicrow.com" > ./dist/CNAME && touch .nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: master
          publish_dir: ./dist
