name: CI

env:
  CNAME: elicrow.com

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Packages
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_OUIJA_SERVER_URL: https://ouija-nzahuayy2a-uc.a.run.app

      - name: Add Required Files
        run: echo "elicrow.com" > ./dist/CNAME && touch .nojekyll

      - name: Copy index to 404
        run: cp ./dist/index.html ./dist/404.html

      - name: Merge Deploy into Develop
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: deploy
          target_branch: develop
          github_token: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v2
        id: deployment
