name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Vue CLI build
        run: npm run build
      - name: GitHub Pages Deploy
        env: 
          BUILD_DIR: "/dist"
        uses: maxheld83/ghpages@v0.2.1
